version: "3"

networks: 
  default:

services: 
  syncthing-relaysrv:
    image: syncthing/relaysrv
    build:
      args:
        VERSION: ${VERSION}
      context: ./builder
    container_name: syncthing-relaysrv
    volumes:
      - ./workspace:/workspace
    ports:
      - 22067:22067
      - 22070:22070
    networks: 
      - default
